name: task-manager-redis-ci

on:
  workflow_dispatch: 

jobs:
  start:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: docker-compose up -d
  stop:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: docker-compose down
